/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'

// Create Virtual Routes

const IndexLazyImport = createFileRoute('/')()
const AccountIndexLazyImport = createFileRoute('/account/')()
const AccountLogbookprogressLazyImport = createFileRoute(
  '/account/logbookprogress',
)()
const AccountLogbookLazyImport = createFileRoute('/account/logbook')()
const AccountDocumentLazyImport = createFileRoute('/account/document')()
const AccountChangePasswordLazyImport = createFileRoute(
  '/account/changePassword',
)()

// Create/Update Routes

const IndexLazyRoute = IndexLazyImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const AccountIndexLazyRoute = AccountIndexLazyImport.update({
  id: '/account/',
  path: '/account/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/account/index.lazy').then((d) => d.Route))

const AccountLogbookprogressLazyRoute = AccountLogbookprogressLazyImport.update(
  {
    id: '/account/logbookprogress',
    path: '/account/logbookprogress',
    getParentRoute: () => rootRoute,
  } as any,
).lazy(() =>
  import('./routes/account/logbookprogress.lazy').then((d) => d.Route),
)

const AccountLogbookLazyRoute = AccountLogbookLazyImport.update({
  id: '/account/logbook',
  path: '/account/logbook',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/account/logbook.lazy').then((d) => d.Route),
)

const AccountDocumentLazyRoute = AccountDocumentLazyImport.update({
  id: '/account/document',
  path: '/account/document',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/account/document.lazy').then((d) => d.Route),
)

const AccountChangePasswordLazyRoute = AccountChangePasswordLazyImport.update({
  id: '/account/changePassword',
  path: '/account/changePassword',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/account/changePassword.lazy').then((d) => d.Route),
)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/account/changePassword': {
      id: '/account/changePassword'
      path: '/account/changePassword'
      fullPath: '/account/changePassword'
      preLoaderRoute: typeof AccountChangePasswordLazyImport
      parentRoute: typeof rootRoute
    }
    '/account/document': {
      id: '/account/document'
      path: '/account/document'
      fullPath: '/account/document'
      preLoaderRoute: typeof AccountDocumentLazyImport
      parentRoute: typeof rootRoute
    }
    '/account/logbook': {
      id: '/account/logbook'
      path: '/account/logbook'
      fullPath: '/account/logbook'
      preLoaderRoute: typeof AccountLogbookLazyImport
      parentRoute: typeof rootRoute
    }
    '/account/logbookprogress': {
      id: '/account/logbookprogress'
      path: '/account/logbookprogress'
      fullPath: '/account/logbookprogress'
      preLoaderRoute: typeof AccountLogbookprogressLazyImport
      parentRoute: typeof rootRoute
    }
    '/account/': {
      id: '/account/'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountIndexLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/account/changePassword': typeof AccountChangePasswordLazyRoute
  '/account/document': typeof AccountDocumentLazyRoute
  '/account/logbook': typeof AccountLogbookLazyRoute
  '/account/logbookprogress': typeof AccountLogbookprogressLazyRoute
  '/account': typeof AccountIndexLazyRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/account/changePassword': typeof AccountChangePasswordLazyRoute
  '/account/document': typeof AccountDocumentLazyRoute
  '/account/logbook': typeof AccountLogbookLazyRoute
  '/account/logbookprogress': typeof AccountLogbookprogressLazyRoute
  '/account': typeof AccountIndexLazyRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexLazyRoute
  '/account/changePassword': typeof AccountChangePasswordLazyRoute
  '/account/document': typeof AccountDocumentLazyRoute
  '/account/logbook': typeof AccountLogbookLazyRoute
  '/account/logbookprogress': typeof AccountLogbookprogressLazyRoute
  '/account/': typeof AccountIndexLazyRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account/changePassword'
    | '/account/document'
    | '/account/logbook'
    | '/account/logbookprogress'
    | '/account'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account/changePassword'
    | '/account/document'
    | '/account/logbook'
    | '/account/logbookprogress'
    | '/account'
  id:
    | '__root__'
    | '/'
    | '/account/changePassword'
    | '/account/document'
    | '/account/logbook'
    | '/account/logbookprogress'
    | '/account/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  AccountChangePasswordLazyRoute: typeof AccountChangePasswordLazyRoute
  AccountDocumentLazyRoute: typeof AccountDocumentLazyRoute
  AccountLogbookLazyRoute: typeof AccountLogbookLazyRoute
  AccountLogbookprogressLazyRoute: typeof AccountLogbookprogressLazyRoute
  AccountIndexLazyRoute: typeof AccountIndexLazyRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  AccountChangePasswordLazyRoute: AccountChangePasswordLazyRoute,
  AccountDocumentLazyRoute: AccountDocumentLazyRoute,
  AccountLogbookLazyRoute: AccountLogbookLazyRoute,
  AccountLogbookprogressLazyRoute: AccountLogbookprogressLazyRoute,
  AccountIndexLazyRoute: AccountIndexLazyRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.jsx",
      "children": [
        "/",
        "/account/changePassword",
        "/account/document",
        "/account/logbook",
        "/account/logbookprogress",
        "/account/"
      ]
    },
    "/": {
      "filePath": "index.lazy.jsx"
    },
    "/account/changePassword": {
      "filePath": "account/changePassword.lazy.jsx"
    },
    "/account/document": {
      "filePath": "account/document.lazy.jsx"
    },
    "/account/logbook": {
      "filePath": "account/logbook.lazy.jsx"
    },
    "/account/logbookprogress": {
      "filePath": "account/logbookprogress.lazy.jsx"
    },
    "/account/": {
      "filePath": "account/index.lazy.jsx"
    }
  }
}
ROUTE_MANIFEST_END */
