/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from "@tanstack/react-router";

// Import Routes

import { Route as rootRoute } from "./routes/__root";

// Create Virtual Routes

const IndexLazyImport = createFileRoute("/")();
const TopicsIndexLazyImport = createFileRoute("/topics/")();
const NotificationIndexLazyImport = createFileRoute("/notification/")();

// Create/Update Routes

const IndexLazyRoute = IndexLazyImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRoute,
} as any).lazy(() => import("./routes/index.lazy").then((d) => d.Route));

const TopicsIndexLazyRoute = TopicsIndexLazyImport.update({
  id: "/topics/",
  path: "/topics/",
  getParentRoute: () => rootRoute,
} as any).lazy(() => import("./routes/topics/index.lazy").then((d) => d.Route));

const NotificationIndexLazyRoute = NotificationIndexLazyImport.update({
  id: "/notification/",
  path: "/notification/",
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import("./routes/notification/index.lazy").then((d) => d.Route),
);

// Populate the FileRoutesByPath interface

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexLazyImport;
      parentRoute: typeof rootRoute;
    };
    "/notification/": {
      id: "/notification/";
      path: "/notification";
      fullPath: "/notification";
      preLoaderRoute: typeof NotificationIndexLazyImport;
      parentRoute: typeof rootRoute;
    };
    "/topics/": {
      id: "/topics/";
      path: "/topics";
      fullPath: "/topics";
      preLoaderRoute: typeof TopicsIndexLazyImport;
      parentRoute: typeof rootRoute;
    };
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  "/": typeof IndexLazyRoute;
  "/notification": typeof NotificationIndexLazyRoute;
  "/topics": typeof TopicsIndexLazyRoute;
}

export interface FileRoutesByTo {
  "/": typeof IndexLazyRoute;
  "/notification": typeof NotificationIndexLazyRoute;
  "/topics": typeof TopicsIndexLazyRoute;
}

export interface FileRoutesById {
  __root__: typeof rootRoute;
  "/": typeof IndexLazyRoute;
  "/notification/": typeof NotificationIndexLazyRoute;
  "/topics/": typeof TopicsIndexLazyRoute;
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths: "/" | "/notification" | "/topics";
  fileRoutesByTo: FileRoutesByTo;
  to: "/" | "/notification" | "/topics";
  id: "__root__" | "/" | "/notification/" | "/topics/";
  fileRoutesById: FileRoutesById;
}

export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute;
  NotificationIndexLazyRoute: typeof NotificationIndexLazyRoute;
  TopicsIndexLazyRoute: typeof TopicsIndexLazyRoute;
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  NotificationIndexLazyRoute: NotificationIndexLazyRoute,
  TopicsIndexLazyRoute: TopicsIndexLazyRoute,
};

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.jsx",
      "children": [
        "/",
        "/notification/",
        "/topics/"
      ]
    },
    "/": {
      "filePath": "index.lazy.jsx"
    },
    "/notification/": {
      "filePath": "notification/index.lazy.jsx"
    },
    "/topics/": {
      "filePath": "topics/index.lazy.jsx"
    }
  }
}
ROUTE_MANIFEST_END */
